export const queryKeys = {
  complaintLists: ["complaint-lists"],
  complaintList: (scope, filters = {}) => [
    ...queryKeys.complaintLists,
    scope,
    filters,
  ],
  citizenComplaintFeed: (filters = {}) => ["citizen-complaint-feed", filters],
  complaintDetail: (complaintId) => [
    "complaint-detail",
    String(complaintId || ""),
  ],
  analyticsSummary: ["analytics-summary"],
  heatmap: (filters = {}) => ["heatmap", filters],
  workerOverview: ["worker-overview"],
  workerDashboardSummary: ["worker-dashboard-summary"],
  workerActivePreview: ["worker-active-preview"],
  workerAssignedLists: ["worker-assigned-list"],
  workerAssignedList: (filters = {}) => ["worker-assigned-list", filters],
  workerLeaderboard: (period = "weekly") => ["worker-leaderboard", period],
  workerAnalytics: (workerId = "") => ["worker-analytics", String(workerId || "")],
  hodDashboardSummary: ["hod-dashboard-summary"],
  hodComplaintFeed: (filters = {}) => ["hod-complaint-feed", filters],
  hodResolvedFeed: (filters = {}) => ["hod-resolved-feed", filters],
  hodWorkersLists: ["hod-workers-list"],
  hodWorkersList: (filters = {}) => ["hod-workers-list", filters],
  hodInvitations: ["hod-invitations"],
  hodWorkerAssignment: (complaintId = "") => [
    "hod-worker-assignment",
    String(complaintId || ""),
  ],
  notifications: ["notifications"],
  notificationPreferences: ["notification-preferences"],
  notificationHistory: (params = {}) => ["notification-history", params],
  notificationHistoryInfinite: (params = {}) => [
    "notification-history-infinite",
    params,
  ],
  reportStats: (filters = {}) => ["report-stats", filters],
  reportDepartmentBreakdown: (filters = {}) => [
    "report-department-breakdown",
    filters,
  ],
  reportSchedules: (filters = {}) => ["report-schedules", filters],
  adminRecycleBin: ["admin-recycle-bin"],
  adminDashboardHome: ["admin-dashboard-home"],
  nearbyComplaints: ["nearby-complaints"],
  workerCompletedFeed: (filters = {}) => ["worker-completed-feed", filters],
  workerDetail: (workerId = "") => ["worker-detail", String(workerId || "")],
  complaintMessages: (complaintId = "", limit = 50) => [
    "complaint-messages",
    String(complaintId || ""),
    { limit },
  ],
  userProfile: ["user-profile"],
  aiReview: ["ai-review"],
};
